everything added :)
lecrank/calc pull request #1
Opened 2023-04-20 19:07 UTC by lecrank

С предыдущим репозиторием не нашел общего языка - сделал много ошибок при работе с гитом. В этот заливаю все сразу : (

2023-04-20 19:48 UTC, Yu-Leo requested changes
**Всё круто!**

Небольшое замечание по поводу области видимости функций в комментариях прописал. Исправь и скинь на ревью ещё раз. Скорее всего, будем мерджить ветки

Работоспособность решения не проверяю - есть unut-тесты.

2023-04-20 19:48 UTC, Yu-Leo commented on calculator/calculator.go
> +func FindIndex(content string, piece string) []int {
Если эта функция используется только в рамках данного пакета, лучше сделать её приватной. Аналогично проверь остальные

2023-04-20 20:17 UTC, lecrank commented
ИСПРАВЛЕНО

2023-04-23 07:52 UTC, Yu-Leo approved these changes
**Принято!**

2023-04-23 07:53 UTC, merged